services:
  - type: web
    name: gemini-backend
    runtime: python
    pythonVersion: 3.11.9 # ADD THIS LINE to explicitly pin Python 3.11
    buildCommand: python -m pip install -r requirements.txt # Use 'python' (which will be 3.11)
    startCommand: python -m uvicorn app.main:app --host 0.0.0.0 --port 10000 # Use 'python' (which will be 3.11)
    envVars:
      - key: DATABASE_URL
        fromDotEnv: true
      - key: JWT_SECRET_KEY
        fromDotEnv: true
      - key: REDIS_HOST
        fromDotEnv: true
      - key: REDIS_PORT
        fromDotEnv: true
      - key: REDIS_USERNAME
        fromDotEnv: true
      - key: REDIS_PASSWORD
        fromDotEnv: true
      - key: GEMINI_API_KEY
        fromDotEnv: true
      - key: STRIPE_SECRET_KEY
        fromDotEnv: true
      - key: STRIPE_PUBLISHABLE_KEY
        fromDotEnv: true
